### ISSUE TITLE
Kyle Orton hasn't appeared

### ISSUE THREAD

**Issue by ishakir** [ishakir/shakitz-fantasy-football#35]
On the currently running site there is no player called K.Orton and nothing like that on the buffalo bills page. We should work out why this is...

**Comment by MikeSpitz** [comment]
This bug is probably invalid with the coming season (unless it happens again) but we need to implement a test that essentially just checks that the number of players we generate equate to the number of players

**Comment by ishakir** [comment]
Yeah going to close this
