### ISSUE TITLE
Bench of the Week table doesn't sort

### ISSUE THREAD

**Issue by ishakir** [ishakir/shakitz-fantasy-football#48]

**Comment by ishakir** [comment]
Yeah, need to put this into assigns, rather than making calls from javascript. When I do that I'll remember to make sure that stats displayed (other than total bench points) are only shown if the game week they're associated with is finished.

**Comment by MikeSpitz** [comment]
Fixed in 6012c09a7d900bdd58cffeefd36e0c1d20043b47
