### ISSUE TITLE
start_of_first_gameweek is not the start of the first gameweek

### ISSUE THREAD

**Issue by MikeSpitz** [ishakir/shakitz-fantasy-football#50]
Currently in With_Game_Week.rb the start_of_first_gameweek method just gets the active game week and not the first. It should be named accordingly.

Additionally, this logic makes it very difficult to mock time objects to test the locked? method in Game_Week.rb

I suggest we change the method signature of the calling method from

  def self.more_than_time_since_start?(days, hours)

to

  def self.more_than_time_since_start?(days, hours, start_time = Time.now.strftime("%d/%m/%Y"))

We can then also get rid of the first_gameweek_start in settings.yml as it isn't being used anywhere else.

**Comment by MikeSpitz** [comment]
What is the situation on this?

**Comment by ishakir** [comment]
I think this is fixed? Timecop sorts out the testing issue, can you clarify "Currently in With_Game_Week.rb the start_of_first_gameweek method just gets the active game week and not the first. It should be named accordingly." I thought it did return the start of the first gameweek.

**Comment by MikeSpitz** [comment]
Ya, happy to close this off.
