### ISSUE TITLE
Scheduling tidy up

### ISSUE THREAD

**Issue by ishakir** [ishakir/shakitz-fantasy-football#52]
Check that we cover the start to 4 hours after the start of every NFL game for the 2015 season. Check that this applies even after the switch from BST -> GMT.

Also, see if we can find a way to un-hard-code the timezone.

**Comment by ishakir** [comment]
And only schedule if the times are in the future

**Comment by ishakir** [comment]
Make sure stuff scheduled in the past doesn't get run.

**Comment by ishakir** [comment]
Schedule is now rejected is scheduled for a time in the past

**Comment by ishakir** [comment]
New scripts now work, just need to use whenever to write the cron tab and then we're all done (hopefully)

**Comment by MikeSpitz** [comment]
https://giphy.com/gifs/hero0fwar-caddy-shack-ToMjGpz81S7usvTIM8w
