### ISSUE TITLE
Team of the week allows duplicates in flex position

### ISSUE THREAD

**Issue by MikeSpitz** [ishakir/shakitz-fantasy-football#55]
Currently on the team of the week page it is possible for a player to be named twice.

Once in either the WR/TE/K position, and then again in the flex. We should just enact a check to ensure that if a duplicate is found we go to the next highest scoring player.

**Comment by MikeSpitz** [comment]
This is not occurring on the live platform. I feel it may have been a bit of an edge case in pre-season when we had too few players. I'm going to close this one.

**Comment by ishakir** [comment]
Pretty sure this is still and issue, just have too many players on the same number of points. I'll re-open should be easy to look into it.

**Comment by ishakir** [comment]
My bad

**Comment by MikeSpitz** [comment]
MY bad.. definitely still happening.
